# Generated by Django 5.2.5 on 2026-01-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_products',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchased_products',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
