# Generated by Django 5.2.5 on 2026-01-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0004_cart_products_quantity_purchased_products_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_products',
            old_name='cart_saved_product',
            new_name='cart_save_product',
        ),
    ]
