# Generated by Django 5.2.5 on 2026-01-17 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0007_rename_cart_save_product_cartitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='user',
            new_name='cart',
        ),
    ]
