# Generated by Django 5.2.5 on 2026-01-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0010_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_payable',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
