# Generated by Django 5.2.5 on 2026-01-19 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0012_orderitem_delivered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='order',
        ),
    ]
