# Generated by Django 5.2.5 on 2026-01-19 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0013_rename_user_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Purchased_products',
            new_name='product',
        ),
    ]
