# Generated by Django 5.2.5 on 2026-01-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0014_rename_purchased_products_orderitem_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_payable',
            new_name='total_cost',
        ),
    ]
