# Generated by Django 5.2.5 on 2026-01-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0016_alter_order_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivered',
        ),
    ]
