# Generated by Django 5.2.5 on 2026-01-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0022_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profile-images/'),
        ),
    ]
