# Generated by Django 5.2.5 on 2026-01-20 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0023_remove_user_name_profile_name_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='avatar',
        ),
    ]
