# Generated by Django 5.2.5 on 2026-01-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0029_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('Esewa Payment', 'esewa payment'), ('CASH ON DELIVERY', 'Cash on delivery')], default='', max_length=20),
        ),
    ]
