# Generated by Django 5.2.5 on 2026-01-12 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0002_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
