# Generated by Django 5.2.5 on 2026-01-16 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0005_rename_cart_saved_product_cart_products_cart_save_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_cart',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='cart_products',
            new_name='CartItem',
        ),
        migrations.RenameModel(
            old_name='product_details',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='purchased_products',
            new_name='OrderItem',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30, unique=True)),
                ('transaction_uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_products', to='StationaryApp.order'),
        ),
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
