# Generated by Django 5.2.5 on 2026-01-17 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0008_rename_user_cartitem_cart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
