# Generated by Django 5.2.5 on 2026-01-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0018_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('CASH ON DELIVERY', 'Cash on delivery')], default='CASH ON DELIVERY', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
