# Generated by Django 5.2.5 on 2026-01-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0024_remove_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
