# Generated by Django 5.2.5 on 2026-01-20 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0028_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('eSewa Payment', 'esewa payment'), ('CASH ON DELIVERY', 'Cash on delivery')], default='', max_length=20),
        ),
    ]
