# Generated by Django 5.2.8 on 2026-01-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0031_order_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
