# Generated by Django 5.2.8 on 2026-01-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StationaryApp', '0032_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_comments',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='user_comments',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='user_comments',
        ),
    ]
